### ISSUE TITLE
Source code for 8.0

### ISSUE THREAD

**Issue by logic** [franciscofranco/Simple-Reboot-app#10]
I use Simple Reboot from F-Droid (7.0.1) and noticed the Play store had a new release (8.0), but I don't see any commit activity in this repository. Has development moved somewhere else?

(It would be incredibly helpful if releases were tagged as well, since F-Droid can automatically pick those up to trigger builds of new releases, and also for the historical purposes of going back to reconstruct a old version as it was released.)

**Comment by patzzz** [comment]
I have compared AndroidManifest.xml files between both versions and Simple Reboot 8.0 (PlayStore version) has targetSdkVersion="27", which is Android Oreo 8.1 and Simple Reboot 7.0.1 (F-droid version) has targetSdkVersion="25", which is Nougat.

Other changes has been done in code, but they aren't commited in this repository.

@franciscofranco Can you commit 8.0 changes here?

**Comment by patzzz** [comment]
I have compared AndroidManifest.xml files between both versions and Simple Reboot 8.0 (PlayStore version) has targetSdkVersion="27", which is Android Oreo 8.1 and Simple Reboot 7.0.1 (F-droid version) has targetSdkVersion="25", which is Nougat.

Other changes has been done in code, but they aren't commited in this repository.

@franciscofranco Can you commit 8.0 changes here?

Thanks.

**Comment by franciscofranco** [comment]
Sure.

**Comment by IzzySoft** [comment]
@franciscofranco if you could [tag your releases](https://github.com/franciscofranco/Simple-Reboot-app/releases), F-Droid could be set to auto-update whenever you publish a new release. Currently, we have a similar situation again: F-Droid is stuck to 8.1, while you've published 8.2 to Play almost half a year ago. Any chance? Thanks in advance!

**Comment by franciscofranco** [comment]
Sure thing. I will do that in a sec.

**Comment by IzzySoft** [comment]
Great, thanks! For naming conventions, I'd suggest using `v<versionName>` as the tag name – e.g. `v8.2` for the current release. That way tags can be matched against your `build.gradle`, and auto-update-check can be enabled (I'd take care of that part then, being one of the F-Droid maintainers).

If you prefer (or it would make things easier for you), something like `c<versionCode>`, currently `c1803261730` would also work. The `v` and `c` are just prefixes picked to make sure the name is recognized as string; you could as well use a different prefix, like `release-`. Ideally, have no spaces in the tag name :wink:

**Comment by franciscofranco** [comment]
I just pushed the tag as v8.3. See if that's ok to you!

**Comment by IzzySoft** [comment]
Thanks a lot – that looks perfect! Enabling auto-update-check then ([see here](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7494)).

With everything working that fine, may I also suggest establishing [Fastlane structures](https://gitlab.com/snippets/1895688) in your repo here? Details behind the link, TL;DR: you can manage summary, description, screenshots and more in your repo, and F-Droid would automatically pick that up with the next tag (you can also use that for deploying to Play Store btw, which is why it's called "Fastlane Supply"). To get you started (mentioned files meant to be inside `fastlane/metadata/android/`):

* `en-US/short_description.txt`: "Make reboots great again - one restart at a time"
* `en-US/full_description.txt`: simply copy over the description from your Play Store listing :wink:
* `en-US/images/phoneScreenshots`: just copy your screenshots here
* `de/short_description.txt`: "Neustarts wieder einfach machen – ein gezielter Neustart"

That would be a good start and can be built upon. Should you do so, please let me know once it's ready and tagged – so I can take care at F-Droid's end that it's used (currently, it would be overridden by our local data, which I'd then need to remove to make it work). Btw: we've got a bunch of `short_descriptions` for other languages via Weblate which you could pick from if you like (the two above are taken from there). Let me know if you need help finding them :wink:

**Comment by franciscofranco** [comment]
Can you make a pull request?

**Comment by IzzySoft** [comment]
There you go :smiley:
